[versions]
kotlin = "2.0.0-Beta4"

[libraries]
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.6.3" }

kotlinCompilerTester = { module = "dev.zacsweers.kctfork:core", version = "0.5.0-alpha04" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.0-Beta4-1.0.18" }
serviceloader = { id = "app.softwork.serviceloader", version = "0.0.8" }
