[versions]
kotlin = "2.0.0"

[libraries]
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }

kotlinCompilerTester = { module = "dev.zacsweers.kctfork:core", version = "0.5.0" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.0-1.0.22" }
serviceloader = { id = "app.softwork.serviceloader", version = "0.0.8" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
