name: Release

on:
  release:
    types: [ created ]

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Set environment for version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true
      - name: Publish
        run: ./gradlew -Pversion=$version -Dorg.gradle.parallel=false --no-configuration-cache publish closeAndReleaseStagingRepositories
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONARTYPE_APIKEY }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONARTYPE_APITOKEN }}

      - name: Create docs
        run: ./gradlew :dokkaHtmlMultiModule --no-configuration-cache
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/dokka/htmlMultiModule
      - name: Deploy Documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
